<<<<<<< HEAD
# Generated by Django 5.1.3 on 2024-11-25 14:53
=======
# Generated by Django 5.1.3 on 2024-12-04 20:34
>>>>>>> d422ca7c77432807b2a57f97bca0e5b29a8cef4b

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceRequestForm",
            fields=[
<<<<<<< HEAD
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "client_company_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "client_company_address",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                (
                    "client_coordinates",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "client_closest_landmark",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "client_contact_person",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "client_designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "client_department",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "client_mobile_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "client_email",
                    models.EmailField(blank=True, max_length=100, null=True),
                ),
                (
                    "srf_service_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "srf_select_power",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "srf_select_space",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "srf_last_mile_mode_of_connection",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "srf_microwave_mast_availability_height",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "srf_interface_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "srf_bandwidth",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "srf_no_of_intended_user",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "lan_mode_of_connection",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "lan_router_availability",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "lan_preferred_router_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "lan_switch_availability",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "lan_preferred_switch_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "lan_existing_equipment",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "lan_rack_space_availability",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "lan_rack_type_and_size",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "lan_specify_others",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "lan_supply_rack",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "lan_power_terminal_availability",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("vpn_mode", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "vpn_point_a",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vpn_point_b",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vpn_vlan_tag",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vpn_mtu_size",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vpn_latency",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("vpn_jilter", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "vpn_p2mp_sink_location",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vps_no_of_virtual_machine",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vps_cpu_cores",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vps_memory_size",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vps_storage_size",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vps_operating_system",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("vps_suite", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "vps_other_details",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "voice_switch_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "voice_ip_phones_required",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "voice_type_no_of_IP_phones",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "voice_gateway_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "others_other_details",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("lead_generation_status", models.BooleanField(default=False)),
                ("client_engagment_status", models.BooleanField(default=False)),
                ("proposal_submission_status", models.BooleanField(default=False)),
                ("quote_submission_status", models.BooleanField(default=False)),
                ("quote_acceptance_status", models.BooleanField(default=False)),
                ("po_receipt_status", models.BooleanField(default=False)),
                ("payment_status", models.BooleanField(default=False)),
                (
                    "upload_quote",
                    models.FileField(blank=True, null=True, upload_to="quote/"),
                ),
                (
                    "upload_proposal",
                    models.FileField(blank=True, null=True, upload_to="proposal/"),
                ),
                (
                    "upload_sla",
                    models.FileField(blank=True, null=True, upload_to="SLA/"),
                ),
                (
                    "upload_receipt",
                    models.FileField(blank=True, null=True, upload_to="receipt/"),
                ),
=======
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('client_company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_company_address', models.CharField(blank=True, max_length=400, null=True)),
                ('client_coordinates', models.CharField(blank=True, max_length=100, null=True)),
                ('client_closest_landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('client_contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('client_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('client_department', models.CharField(blank=True, max_length=100, null=True)),
                ('client_mobile_number', models.CharField(blank=True, max_length=100, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('srf_service_type', models.CharField(blank=True, max_length=100, null=True)),
                ('srf_select_power', models.CharField(blank=True, max_length=100, null=True)),
                ('srf_select_space', models.CharField(blank=True, max_length=100, null=True)),
                ('srf_last_mile_mode_of_connection', models.CharField(blank=True, max_length=100, null=True)),
                ('srf_microwave_mast_availability_height', models.CharField(blank=True, max_length=100, null=True)),
                ('srf_interface_type', models.CharField(blank=True, max_length=100, null=True)),
                ('srf_bandwidth', models.CharField(blank=True, max_length=100, null=True)),
                ('srf_no_of_intended_user', models.CharField(blank=True, max_length=100, null=True)),
                ('lan_mode_of_connection', models.CharField(blank=True, max_length=100, null=True)),
                ('lan_router_availability', models.CharField(blank=True, max_length=100, null=True)),
                ('lan_preferred_router_type', models.CharField(blank=True, max_length=100, null=True)),
                ('lan_switch_availability', models.CharField(blank=True, max_length=100, null=True)),
                ('lan_preferred_switch_type', models.CharField(blank=True, max_length=100, null=True)),
                ('lan_existing_equipment', models.CharField(blank=True, max_length=100, null=True)),
                ('lan_rack_space_availability', models.CharField(blank=True, max_length=100, null=True)),
                ('lan_rack_type_and_size', models.CharField(blank=True, max_length=100, null=True)),
                ('lan_specify_others', models.CharField(blank=True, max_length=100, null=True)),
                ('lan_supply_rack', models.CharField(blank=True, max_length=100, null=True)),
                ('lan_power_terminal_availability', models.CharField(blank=True, max_length=100, null=True)),
                ('vpn_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('vpn_point_a', models.CharField(blank=True, max_length=100, null=True)),
                ('vpn_point_b', models.CharField(blank=True, max_length=100, null=True)),
                ('vpn_vlan_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('vpn_mtu_size', models.CharField(blank=True, max_length=100, null=True)),
                ('vpn_latency', models.CharField(blank=True, max_length=100, null=True)),
                ('vpn_jilter', models.CharField(blank=True, max_length=100, null=True)),
                ('vpn_p2mp_sink_location', models.CharField(blank=True, max_length=100, null=True)),
                ('vps_no_of_virtual_machine', models.CharField(blank=True, max_length=100, null=True)),
                ('vps_cpu_cores', models.CharField(blank=True, max_length=100, null=True)),
                ('vps_memory_size', models.CharField(blank=True, max_length=100, null=True)),
                ('vps_storage_size', models.CharField(blank=True, max_length=100, null=True)),
                ('vps_operating_system', models.CharField(blank=True, max_length=100, null=True)),
                ('vps_suite', models.CharField(blank=True, max_length=100, null=True)),
                ('vps_other_details', models.CharField(blank=True, max_length=100, null=True)),
                ('voice_switch_type', models.CharField(blank=True, max_length=100, null=True)),
                ('voice_ip_phones_required', models.CharField(blank=True, max_length=100, null=True)),
                ('voice_type_no_of_IP_phones', models.CharField(blank=True, max_length=100, null=True)),
                ('voice_gateway_type', models.CharField(blank=True, max_length=100, null=True)),
                ('others_other_details', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_generation_status', models.BooleanField(default=False)),
                ('client_engagment_status', models.BooleanField(default=False)),
                ('proposal_submission_status', models.BooleanField(default=False)),
                ('quote_submission_status', models.BooleanField(default=False)),
                ('quote_acceptance_status', models.BooleanField(default=False)),
                ('po_receipt_status', models.BooleanField(default=False)),
                ('payment_status', models.BooleanField(default=False)),
                ('upload_quote', models.FileField(blank=True, null=True, upload_to='quote/')),
                ('upload_proposal', models.FileField(blank=True, null=True, upload_to='proposal/')),
                ('upload_sla', models.FileField(blank=True, null=True, upload_to='SLA/')),
                ('upload_receipt', models.FileField(blank=True, null=True, upload_to='receipt/')),
>>>>>>> d422ca7c77432807b2a57f97bca0e5b29a8cef4b
            ],
        ),
    ]
