# Generated by Django 5.1.3 on 2024-11-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequestform',
            name='srf_service_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
