# Generated by Django 5.1.3 on 2024-11-25 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="servicerequestform",
            old_name="client_engagment_status",
            new_name="client_engagement_status",
        ),
    ]
