# Generated by Django 5.1.3 on 2024-11-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0002_servicerequestform_srf_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequestform',
            name='upload_proposal',
            field=models.FileField(blank=True, null=True, upload_to='proposal/'),
        ),
        migrations.AddField(
            model_name='servicerequestform',
            name='upload_quote',
            field=models.FileField(blank=True, null=True, upload_to='quote/'),
        ),
        migrations.AddField(
            model_name='servicerequestform',
            name='upload_receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipt/'),
        ),
        migrations.AddField(
            model_name='servicerequestform',
            name='upload_sla',
            field=models.FileField(blank=True, null=True, upload_to='SLA/'),
        ),
    ]
