# Generated by Django 5.1.3 on 2024-11-22 11:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0003_servicerequestform_upload_proposal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequestform',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
